-- 管理员对组织/权限/系统设置类模块仅保留查看与 GET 查询。可重复执行。

DELETE rp
FROM sys_role_permission rp
JOIN sys_role r ON r.id = rp.role_id AND r.code = 'ADMIN'
JOIN sys_permission p ON p.id = rp.permission_id
WHERE p.code IN (
    'permission-content:create',
    'permission-content:table-edit',
    'permission-content:table-delete',
    'api:POST:/api/permissions',
    'api:PUT:/api/permissions/{id}',
    'api:DELETE:/api/permissions/{id}',
    'route:create',
    'route:update',
    'route:delete',
    'route:add-child',
    'route:generate',
    'route:table-edit',
    'route:table-delete',
    'api:POST:/api/routes',
    'api:PUT:/api/routes/{id}',
    'api:DELETE:/api/routes/{id}',
    'api:POST:/api/routes/batch-delete',
    'api:POST:/api/routes/{id}/generate',
    'role:create',
    'role:update',
    'role:delete',
    'role:assign',
    'role:table-edit',
    'role:table-delete',
    'api:POST:/api/roles',
    'api:PUT:/api/roles/{id}',
    'api:DELETE:/api/roles/{id}',
    'api:PUT:/api/roles/{id}/permissions',
    'api:PUT:/api/roles/{id}/status',
    'api:POST:/api/roles/batch-delete',
    'user:create',
    'user:update',
    'user:delete',
    'user:import',
    'user:export',
    'user:table-edit',
    'user:table-delete',
    'api:POST:/api/users',
    'api:PUT:/api/users/{id}',
    'api:DELETE:/api/users/{id}',
    'api:PATCH:/api/users/{id}/status',
    'api:POST:/api/users/batch-delete',
    'api:POST:/api/users/import',
    'api:GET:/api/users/export',
    'unit:create',
    'unit:update',
    'unit:delete',
    'unit:add-child',
    'unit:assign',
    'unit:table-edit',
    'unit:table-delete',
    'api:POST:/api/units',
    'api:PUT:/api/units/{id}',
    'api:DELETE:/api/units/{id}',
    'api:POST:/api/units/batch-delete',
    'api:PUT:/api/units/{id}/status',
    'api:PUT:/api/units/{id}/roles',
    'post:create',
    'post:update',
    'post:delete',
    'post:import',
    'post:export',
    'post:table-edit',
    'post:table-delete',
    'api:POST:/api/posts',
    'api:PUT:/api/posts/{id}',
    'api:DELETE:/api/posts/{id}',
    'api:POST:/api/posts/batch-delete',
    'api:PUT:/api/posts/{id}/status',
    'api:POST:/api/posts/import',
    'api:GET:/api/posts/export',
    'system-config:update',
    'api:POST:/api/system-config/upload',
    'api:PUT:/api/system-config/app',
    'api:PUT:/api/system-config/session',
    'api:PUT:/api/system-config/ui',
    'api:PUT:/api/system-config/log-retention',
    'api:PUT:/api/system-config/sensitive-data',
    'remote-storage:create',
    'remote-storage:update',
    'remote-storage:delete',
    'remote-storage:table-edit',
    'remote-storage:table-delete',
    'api:PUT:/api/system-config/storage',
    'api:PUT:/api/site-contact',
    'api:POST:/api/site-contact/upload',
    'security-policy:update',
    'security-policy:table-unlock',
    'api:PUT:/api/security-policy',
    'api:DELETE:/api/security-policy/locks/{username}'
);

UPDATE sys_role
SET description = '日常管理；组织/权限/系统设置类模块仅可查看'
WHERE code = 'ADMIN';
